name: First Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Print Hello World
              run: echo "Hello World"
            
            - name: Print Current Directory
              run: pwd

            - name: List Files
              run: ls -l